#! /bin/sh

xsetroot -cursor_name left_ptr & 

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width          3
bspc config window_gap            10
bspc config normal_border_color   "#fdf6e3"
bspc config focused_border_color  "#475b62"
bspc config presel_feedback_color "#fdf6e3"

bspc config top_padding           15
bspc config right_padding         15
bspc config bottom_padding        15
bspc config left_padding          15


bspc config split_ratio           0.65
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config automatic_scheme      alternate

bspc rule -a Emacs=tiled
