#! /bin/sh

xsetroot -cursor_name left_ptr & 

bspc monitor -d 1 2 3 4 5 6

bspc config border_width          3
bspc config window_gap            10
bspc config normal_border_color   "#eaeaea"
bspc config focused_border_color  "#455e7e"
bspc config presel_feedback_color "#ffdee2"

bspc config top_padding           10
bspc config right_padding         10
bspc config bottom_padding        10
bspc config left_padding          10


bspc config split_ratio           0.65
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config automatic_scheme      alternate
